import type { AgentState } from './types';
import { MODEL, createInitialMessages } from '@/config';

export const createInitialState = (): AgentState => ({
  messages: createInitialMessages(),
  inputChars: [],
  pasteRanges: [],
  historyEntries: [],
  queuedSubmissions: [],
  pendingSteers: [],
  cursor: 0,
  busy: false,
  busyStatusText: null,
  closed: false,
  liveAssistantText: '',
  liveReasoningText: '',
  selectedSuggestion: 0,
  currentModel: MODEL,
  thinkingMode: 'auto',
  fastModeEnabled: false,
  lastPromptTokens: 0,
  lastOutputTokens: 0,
  lastReasoningTokens: 0,
  livePromptTokens: 0,
  liveOutputTokens: 0,
  liveReasoningTokens: 0,
  totalCost: 0,
  abortController: null,
  abortRequested: false,
  steerRequested: false,
  pendingApproval: null,
  pendingChoice: null,
  pendingChoiceIndex: 0,
  footerNotice: null,
  sessionFileChanges: [],
  permissionMode: 'ask',
  autoCompactEnabled: true,
  planningMode: false,
  showThinking: true,
  compacting: false,
  sideConversation: null,
});
